version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "9000:4000"
    environment:
      # Estas URLs apuntan a tus microservicios en el host (puertos 8080 y 8081)
      GX_BE_PROASIG_URL: "http://host.docker.internal:8080/graphql"
      GX_BE_CALIF_URL: "http://host.docker.internal:8081/graphql"
      PORT: 4000
    # Agregamos este bloque para que "host.docker.internal" se resuelva a la IP del host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
